export { default as Piscina } from './Piscina'
export { default as Cama } from './Cama'
export { default as Aire } from './Aire'
export { default as Wifi } from './Wifi'
export { default as Tv } from './Tv'
